// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DashboardController from "./dashboard_controller"
application.register("dashboard", DashboardController)

import HeadbarController from "./headbar_controller"
application.register("headbar", HeadbarController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import FilePreviewController from "./file_preview_controller"
application.register("file-preview", FilePreviewController)

import EnableSubmitButtonController from "./enable_submit_button_controller"
application.register("enable-submit-button", EnableSubmitButtonController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import ColorPickerController from "./color_picker_controller"
application.register("color-picker", ColorPickerController)

